### ISSUE TITLE
Build tutorial: PATH_TO_MICRO_FOCUS_BUILD_TOOLS_DOCKER_IMAGE, where is the image?

### ISSUE THREAD

**Issue by ssamayoa** [awsdocs/aws-m2-user-guide#2]
Build tutorial mentions PATH_TO_MICRO_FOCUS_BUILD_TOOLS_DOCKER_IMAGE but, where is the image?

Without the tools image is impossible to build any application and of course cannot deploy it on M2 runtime.

File:
https://github.com/awsdocs/aws-m2-user-guide/blob/main/doc_source/tutorial-build.md

**Comment by macaller** [comment]
Thank you for telling me about this issue. I'll work on it and will provide updates here on the progress.

**Comment by macaller** [comment]
I've updated the docs to clarify that the image isn't yet publicly available. Thanks for the feedback.
