### ISSUE TITLE
Build tutorial links to compiled code instead of source

### ISSUE THREAD

**Issue by paulovitorjp** [awsdocs/aws-m2-user-guide#4]
In the build tool tutorial, where it should be linking the source code to be built, it is actually linking to the same compiled code used in the runtime tutorial:

https://docs.aws.amazon.com/m2/latest/userguide/tutorial-build.html#:~:text=Download%20the%20BankDemo%20sample%20application

Expected behavior: Link to the source code, not compiled code, to be built during the tutorial.

**Comment by macaller** [comment]
Thank you for telling me about this issue. I'll be working on it and will provide updates here about progress.

**Comment by macaller** [comment]
Link is corrected. Thanks again for the feedback.
