### ISSUE TITLE
JSON with dataset configuration being displayed when it isn't required in Runtime Tutorial

### ISSUE THREAD

**Issue by paulovitorjp** [awsdocs/aws-m2-user-guide#5]
In the runtime tutorial, when it instructs the user to upload the catalog files into an S3 bucket. It shows the JSON configuration of the datasets, and tells the user to replace the bucket name. This is confusing because it give the impression the user needs that file at this time, and that it needs to make those changes.

https://docs.aws.amazon.com/m2/latest/userguide/tutorial-runtime.html#:~:text=The%20following%20JSON%20shows%20all%20the%20required%20data%20sets.%20Replace%20%24S3_DATASET_PREFIX%20with%20your%20Amazon%20S3%20bucket%20that%20contains%20the%20catalog%20data.%20For%20example%2C%20m2%2Dtutorial/catalog.

This file is actually necessary when you are importing the datasets on Step 4, and for some reason it is showing the import by adding each file manually, when the user could use the JSON configuration showed earlier.

**Comment by macaller** [comment]
Thank you for telling me about this issue. I'll be working on it and will provide updates here about progress.

**Comment by macaller** [comment]
This fix is now live. See [Step 4: Import data sets](https://docs.aws.amazon.com/m2/latest/userguide/tutorial-runtime.html#tutorial-runtime-step4)
