### ISSUE TITLE
Missing information on how to find DNS name for Rumba connection - Managed Runtime Tutorial

### ISSUE THREAD

**Issue by paulovitorjp** [awsdocs/aws-m2-user-guide#6]
On Step 6 of the ManagedRuntime tutorial, it shows where to configure the connection parameters including dns name and port on Rumba. But it does not say where to get that information. 

https://docs.aws.amazon.com/m2/latest/userguide/tutorial-runtime.html#:~:text=changes%20to%20Running.-,Step%206%3A%20Connect%20to%20the%20BankDemo%20sample%20application,-Start%20the%20terminal

Expected behavior: 
Have instructions on where to get it from the EC2 Console - Load balancers, or add the dns names to the runtime console.

**Comment by macaller** [comment]
Thank you for telling me about this issue. I will be working on it and will provide updates here about progress.

**Comment by macaller** [comment]
This issue is resolved. See [Step 6: Connect to the BankDemo sample application](https://docs.aws.amazon.com/m2/latest/userguide/tutorial-runtime.html#tutorial-runtime-step6)
