### ISSUE TITLE
set-up-ed.md doc. Step2

### ISSUE THREAD

**Issue by jpent** [awsdocs/aws-m2-user-guide#8]
Step 2 - T
The rclone.bat in the public folder needs to be updated.  This is not a documentation error but the file itself needs to be updated.
The path is incorrect : Currently has C:\Public\Users\Public\rclone mount m2-s3:<your-bucket>/ S: --config "D:\PhotonUse...

should be C:\Users\Public\rclone. (not C:\Public).

- Documentation update suggestion: 
It has copy rclone.bat mentioned twice, I suppose one of that should be copy the config and update it . It may be beneficial to say copy .bat and conf in bullet point 1 and remove the copy rcolne.bat from bullet 3.

**Comment by macaller** [comment]
Thank you for telling me about this issue. I will let the team know about the contents of the rclone.bat file, and will be working on the doc update as well. I will provide updates here about progress.

**Comment by macaller** [comment]
This issue has been resolved.
